version: '2.6.1'
services:
  dev-db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=locus_coffee
    networks:
      - aflowchars
networks:
  aflowchars:
